"""Shared library for chess-vibe: UCI client, time control models, engine registry, and storage."""

from shared.engine_registry import EngineEntry, EngineRegistryError, load_registry
from shared.storage import (
    Engine,
    FileGameRepository,
    FileSPRTTestRepository,
    Game,
    GameFilter,
    GameRepository,
    GameResult,
    Move,
    OpeningBook,
    SPRTOutcome,
    SPRTStatus,
    SPRTTest,
    SPRTTestFilter,
    SPRTTestRepository,
    export_game_to_pgn,
)
from shared.time_control import (
    DepthTimeControl,
    FixedTimeControl,
    IncrementTimeControl,
    NodesTimeControl,
    TimeControl,
    TimeControlType,
    parse_time_control,
)
from shared.uci_client import (
    BestMove,
    UCIClient,
    UCIEngineError,
    UCIError,
    UCIInfo,
    UCIScore,
    UCITimeoutError,
    parse_bestmove,
    parse_info_line,
)
from shared.utils import RepoRootNotFoundError, get_repo_root

__all__ = [
    "BestMove",
    "DepthTimeControl",
    "Engine",
    "EngineEntry",
    "EngineRegistryError",
    "FileGameRepository",
    "FileSPRTTestRepository",
    "FixedTimeControl",
    "Game",
    "GameFilter",
    "GameRepository",
    "GameResult",
    "IncrementTimeControl",
    "Move",
    "NodesTimeControl",
    "OpeningBook",
    "RepoRootNotFoundError",
    "SPRTOutcome",
    "SPRTStatus",
    "SPRTTest",
    "SPRTTestFilter",
    "SPRTTestRepository",
    "TimeControl",
    "TimeControlType",
    "UCIClient",
    "UCIEngineError",
    "UCIError",
    "UCIInfo",
    "UCIScore",
    "UCITimeoutError",
    "export_game_to_pgn",
    "get_repo_root",
    "load_registry",
    "parse_bestmove",
    "parse_info_line",
    "parse_time_control",
]
